name: Phoenix
version: 1.0
main: xyz.phoenix.phoneix.Main
author: Glorial
commands:
    grant:
        usage: /<command> <item>
        description: Used by ops to grant server items.
    perm:
        usage: /<command> <add/remove> <player> <permission>
        description: Used by admins to give people permissions, example, "/perm add Glorial admin", do "/perm list" to see all perms.
    house:
        usage: /<command> switch <player> <house>
        description: Used by admins to switch players houses.

