name: Phoenix
version: 1.0
main: xyz.phoenix.phoneix.Main
author: Glorial
loadbefore: [WorldEdit]
commands:
    grant:
        usage: /<command> <item>
        description: Used by ops to grant server items.
    perm:
        usage: /<command> <add/remove> <player> <permission>
        description: Used by admins to give people permissions, example, "/perm add Glorial admin", do "/perm list" to see all perms.
    house:
        usage: /<command> switch <player> <house>
        description: Used by admins to switch players houses.

    info:
        usage: /<command> <player> [-a]
        description: Used to find the info of a player. The all argument means that it will show you more data.
        aliases: [info]
    casts:
        usage: /<command> <player> <spell>
        description: Sees how many times you have casted spells.
    id:
        usage: /<command>
        description: Gives the player their id card.
    inv:
        usage: /<command> <player>
        description: Used by staff to view players inventory.
        aliases: [inventory]