name: Phoenix
version: 1.0
main: xyz.phoenix.phoneix.Main
authors: [NanMan, Glorial]
commands:
    grant:
        usage: /<command>
        description: Used by ops to grant server items.
    perm:
        usage: /<command>
        description: Used by admins to give people permissions, example, "/perm add Glorial admin", do "/perm list" to see all perms!
